<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="Gridview_and_Detailsview_Project.Default" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:SqlDataSource ID="GridViewSource" runat="server" ConnectionString="<%$ ConnectionStrings:UnitConnection %>" SelectCommand="SELECT * FROM [unitStats]"></asp:SqlDataSource>
        </div>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" BackColor="#DEBA84" BorderColor="#DEBA84" BorderStyle="None" BorderWidth="1px" CellPadding="3" CellSpacing="2" DataKeyNames="Unit" DataSourceID="GridViewSource">
            <Columns>
                <asp:CommandField ShowSelectButton="True" />
                <asp:BoundField DataField="Unit" HeaderText="Unit" ReadOnly="True" SortExpression="Unit" />
                <asp:BoundField DataField="hp" HeaderText="hp" SortExpression="hp" />
                <asp:BoundField DataField="atk" HeaderText="atk" SortExpression="atk" />
                <asp:BoundField DataField="def" HeaderText="def" SortExpression="def" />
                <asp:BoundField DataField="elem" HeaderText="elem" SortExpression="elem" />
            </Columns>
            <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />
            <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />
            <PagerStyle ForeColor="#8C4510" HorizontalAlign="Center" />
            <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />
            <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#FFF1D4" />
            <SortedAscendingHeaderStyle BackColor="#B95C30" />
            <SortedDescendingCellStyle BackColor="#F1E5CE" />
            <SortedDescendingHeaderStyle BackColor="#93451F" />
        </asp:GridView>
        <asp:DetailsView ID="DetailsView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" Height="50px" Width="125px" DataSourceID="DetailsViewSource" AutoGenerateRows="False" DataKeyNames="Unit" OnItemDeleted="DetailsView1_ItemDeleted" OnItemUpdated="DetailsView1_ItemUpdated">
            <Fields>
                <asp:BoundField DataField="Unit" HeaderText="Unit" ReadOnly="True" SortExpression="Unit" />
                <asp:BoundField DataField="hp" HeaderText="hp" SortExpression="hp" />
                <asp:BoundField DataField="atk" HeaderText="atk" SortExpression="atk" />
                <asp:BoundField DataField="def" HeaderText="def" SortExpression="def" />
                <asp:BoundField DataField="elem" HeaderText="elem" SortExpression="elem" />
            </Fields>
        </asp:DetailsView>
        <asp:SqlDataSource ID="DetailsViewSource" runat="server" ConnectionString="<%$ ConnectionStrings:UnitConnection %>" DeleteCommand="DELETE FROM [unitStats] WHERE [Unit] = @Unit" InsertCommand="INSERT INTO [unitStats] ([Unit], [hp], [atk], [def], [elem]) VALUES (@Unit, @hp, @atk, @def, @elem)" SelectCommand="SELECT * FROM [unitStats] WHERE ([Unit] = @Unit)" UpdateCommand="UPDATE [unitStats] SET [hp] = @hp, [atk] = @atk, [def] = @def, [elem] = @elem WHERE [Unit] = @Unit">
            <DeleteParameters>
                <asp:Parameter Name="Unit" Type="String" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="Unit" Type="String" />
                <asp:Parameter Name="hp" Type="Int32" />
                <asp:Parameter Name="atk" Type="Int32" />
                <asp:Parameter Name="def" Type="Int32" />
                <asp:Parameter Name="elem" Type="String" />
            </InsertParameters>
            <SelectParameters>
                <asp:ControlParameter ControlID="GridView1" Name="Unit" PropertyName="SelectedValue" Type="String" />
            </SelectParameters>
            <UpdateParameters>
                <asp:Parameter Name="hp" Type="Int32" />
                <asp:Parameter Name="atk" Type="Int32" />
                <asp:Parameter Name="def" Type="Int32" />
                <asp:Parameter Name="elem" Type="String" />
                <asp:Parameter Name="Unit" Type="String" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </form>
</body>
</html>
