<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="DetailsView.aspx.cs" Inherits="DatabaseConnection.DetailsView" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT * FROM [Cars]"></asp:SqlDataSource>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" BackColor="White" BorderColor="#3366CC" BorderStyle="None" BorderWidth="1px" CellPadding="4" DataKeyNames="vin" DataSourceID="SqlDataSource1">
                <Columns>
                    <asp:CommandField ShowSelectButton="True" />
                    <asp:BoundField DataField="vin" HeaderText="vin" ReadOnly="True" SortExpression="vin" />
                    <asp:BoundField DataField="make" HeaderText="make" SortExpression="make" />
                    <asp:BoundField DataField="model" HeaderText="model" SortExpression="model" />
                    <asp:BoundField DataField="year" HeaderText="year" SortExpression="year" />
                    <asp:BoundField DataField="condition" HeaderText="condition" SortExpression="condition" />
                </Columns>
                <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
                <HeaderStyle BackColor="#003399" Font-Bold="True" ForeColor="#CCCCFF" />
                <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
                <RowStyle BackColor="White" ForeColor="#003399" />
                <SelectedRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
                <SortedAscendingCellStyle BackColor="#EDF6F6" />
                <SortedAscendingHeaderStyle BackColor="#0D4AC4" />
                <SortedDescendingCellStyle BackColor="#D6DFDF" />
                <SortedDescendingHeaderStyle BackColor="#002876" />
            </asp:GridView>
        </div>     
        <asp:DetailsView ID="DetailsView1" runat="server" AutoGenerateRows="False" DataKeyNames="vin" DataSourceID="SqlDataSourceDetailsView" Height="50px" Width="125px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnPageIndexChanging="DetailsView1_PageIndexChanging" OnItemDeleted="DetailsView1_ItemDeleted">
            <Fields>
                <asp:BoundField DataField="vin" HeaderText="vin" ReadOnly="True" SortExpression="vin" />
                <asp:BoundField DataField="make" HeaderText="make" SortExpression="make" />
                <asp:BoundField DataField="model" HeaderText="model" SortExpression="model" />
                <asp:BoundField DataField="year" HeaderText="year" SortExpression="year" />
                <asp:BoundField DataField="condition" HeaderText="condition" SortExpression="condition" />
            </Fields>
        </asp:DetailsView>
        <asp:SqlDataSource ID="SqlDataSourceDetailsView" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT * FROM [Cars] WHERE ([vin] = @vin)" DeleteCommand="DELETE FROM [Cars] WHERE [vin] = @vin" InsertCommand="INSERT INTO [Cars] ([vin], [make], [model], [year], [isUnderInspection]) VALUES (@vin, @make, @model, @year, @isUnderInspection)" UpdateCommand="UPDATE [Cars] SET [make] = @make, [model] = @model, [year] = @year, [isUnderInspection] = @isUnderInspection WHERE [vin] = @vin">
            <DeleteParameters>
                <asp:Parameter Name="vin" Type="String" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="vin" Type="String" />
                <asp:Parameter Name="make" Type="String" />
                <asp:Parameter Name="model" Type="String" />
                <asp:Parameter Name="year" Type="String" />
                <asp:Parameter Name="isUnderInspection" Type="Boolean" />
            </InsertParameters>
            <SelectParameters>
                <asp:ControlParameter ControlID="GridView1" Name="vin" PropertyName="SelectedValue" Type="String" DefaultValue="-1" />
            </SelectParameters>
            <UpdateParameters>
                <asp:Parameter Name="make" Type="String" />
                <asp:Parameter Name="model" Type="String" />
                <asp:Parameter Name="year" Type="String" />
                <asp:Parameter Name="isUnderInspection" Type="Boolean" />
                <asp:Parameter Name="vin" Type="String" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </form>
</body>
</html>
